config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  get '/users/search', to: 'users#search'
  resources :groups, only: [:index, :new, :create, :show, :edit, :update] do
   resources :messages, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :group_name, presence: true

  has_many :users, through: :groups_users
  has_many :groups_users
  has_many :messages
  accepts_nested_attributes_for :groups_users

end

app/models/groups_user.rb
class GroupsUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader

  def date
    created_at.strftime("%Y/%m/%d %H:%M:%S")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups_users
  has_many :groups, through: :groups_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def before_sign_in_path_for(resource)
    new_user_session_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update]

  def index
    @groups = group_list
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: 'グループが作成されました。'
    else
      flash.now[:alert] = 'グループ名を入力してください。'
      render :new
    end
  end

  def show
    @groups = group_list
  end

  def edit
  end

  def update
    if @group.update(group_params)
       redirect_to group_messages_path(@group), notice: 'グループが編集されました。'
    else
      flash.now[:alert] = 'グループ名を入力してください。'
      render :edit
    end
  end


  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:group_name, user_ids: [])
  end

  def group_list
    Group.includes(:users).where(groups_users: {user_id: current_user.id})
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

 def index
  @groups = group_list
  @group = Group.find(params[:group_id])
  @message = Message.new
  @messages = @group.messages.includes(:user)
  respond_to do |format|
      format.html
      format.json {
        message_array = []
        @messages.each do |message|
          message_array << {
            body: message.body,
            name: message.user.name,
            image_url: message.image.url,
            created_at: message.created_at.strftime("%Y/%m/%d %H:%M:%S")
          }
        end
        render json: {
          message: message_array
    }
  }
  end
 end

 def create
  @message = current_user.messages.new(message_params)
  if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path, notice: 'メッセージを保存しました。' }
        format.json { render json:{
          body: @message.body,
          image: @message.image.url,
          name: @message.user.name,
          created_at: @message.date
          }
        }
      end
    else
      redirect_to group_messages_path , alert: 'メッセージを記入してください。'
    end
 end

 private

 def message_params
  params.require(:message).permit(:body, :image, :group_id).merge(group_id: params[:group_id])
 end

 def group_list
  Group.includes(:users).where(groups_users: {user_id: current_user.id})
 end

 def group_params
  params.require(:group).permit(:group_name, {user_ids: []})
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
     name = "%#{params[:keyword]}%"
     @users = User.where('name LIKE ? and not id = ?', name, current_user.id)
     render json: @users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_name"} グループ名
    .chat-group-form__field--right
      = f.text_field :group_name, id: "chat_group_name", class: "chat-group-form__input", placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for:  "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        .chat-group-user.clearfix
          = hidden_field_tag 'group[user_ids][]', current_user.id
          %p.chat-group-user__name= current_user.name
        - @group.users.each do |user|
          - if(user.id != current_user.id)
            .chat-group-user.clearfix
              = hidden_field_tag 'group[user_ids][]', user.id
              %p.chat-group-user__name
                = user.name
              = content_tag "a", '削除', class: "user-search-remove chat-group-user__btn chat-group-user__btn--remove", data: { user: { id: user.id }}
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "Save", class: "chat-group-form__action-btn"

app/views/groups/_sidebar.html.haml
.chat-side
  .chat-user.clearfix
    %h5
      = current_user.name
    .chat-user__actions
      %a.chat-user__action
      = link_to new_group_path, class: "chat-user__action" do
        %i.fa.fa-pencil-square-o
      %a.chat-user__action
      = link_to edit_user_registration_path, class: "chat-user__action" do
        %i.fa.fa-cog
  %ul.chat-groups
    - @groups.each do |group|
      %li.chat-group
        = link_to group_messages_path(group), class: "chat-group-link" do
          %p.chat-group__name
            = simple_format(group.group_name)
          %p.chat-group__message
            -if last_message = group.messages.last
              = last_message.body
            -else
              = "まだメッセージはありません。"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form'

app/views/groups/index.html.haml
.chat.clearfix
  = render 'sidebar', group: @group

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content =>  "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/messages/_message.html.haml
%ul.chat-messages
  - @group.messages.each do |message|
    %li.chat-message
      .chat-mssage__header.clearfix
        %p.chat-message__name
          = message.user.name
        %p.chat-message__time
          = message.created_at.strftime("%Y-%m-%d %H:%M:%S")
      %p.chat-message__body
        = message.body
          - if message.image.url
          %br= image_tag message.image.url

app/views/messages/index.html.haml
.chat.clearfix
  = render '/groups/sidebar', group: @group
  .chat-main
    .chat-header.clearfix
      .chat-header--left
        %h2
          = @group.group_name
        %p.chat-header__users<>
          Member:
          %span.chat-header__user
          - @group.users.each do |user|
            = user.name
      .chat-header--right
        = link_to 'Edit', edit_group_path(@group), class: "chat-header__edit-btn", method: :get
    .chat-body
      = render 'message'
    .chat-footer
      = form_for [@group, @message], id: "new_message", class:"new_message" do |f|
        .chat-footer__body
          = f.text_area :body, id: "message_content", class: "message_body", placeholder: "type a message", rows: "1"
          %label.chat-footer__image
            = f.file_field :image, style: "display:none;"
            %i.fa.fa-image
        = f.submit "Save", class: "input", method: :post